# main settings
FPS = 60
WIDTH = 750
HEIGHT = 750
INITIAL_LIVES = 5

# main menu
LOGO_WIDTH = 375
LOGO_HEIGHT = 100
LOGO_Y_POSITION = 100
MENU_ITEM_TOP_MARGIN = 20
MENU_ITEM_COLOR = (255, 255, 255)
START_GAME_LABEL = "START GAME"
EXIT_LABEL = "EXIT"

# paddle
PADDLE_WIDTH = 100
PADDLE_HIGH = 20
PADDLE_HORIZONTAL_VELOCITY = 5
PADDLE_INITIAL_X_POSITION = WIDTH / 2
PADDLE_INITIAL_Y_POSITION = HEIGHT - 100

# brick
BRICKS_AMOUNT_PER_LINE = 10
MAX_LINES_OF_BRICKS_AMOUNT = 10
BRICK_WIDTH = 75
BRICK_HEIGHT = 25

# ball
BALL_WIDTH = 20
BALL_HEIGHT = 20
BALL_ABSOLUTE_VERTICAL_VELOCITY = 6
BALL_INITIAL_X_POSITION = PADDLE_INITIAL_X_POSITION + PADDLE_WIDTH / 2 - BALL_WIDTH / 2
BALL_INITIAL_Y_POSITION = PADDLE_INITIAL_Y_POSITION - BALL_HEIGHT
