# main settings
FPS = 60
WIDTH = 750
HEIGHT = 750
INITIAL_LIVES = 1

# main menu
LOGO_WIDTH = 375
LOGO_HEIGHT = 100
LOGO_Y_POSITION = 100
MENU_ITEM_TOP_MARGIN = 20
MENU_ITEM_COLOR = (255, 255, 255)
START_GAME_LABEL = "START GAME"
EXIT_LABEL = "EXIT"

# paddle
PADDLE_WIDTH = 100
PADDLE_HIGH = 20
PADDLE_HORIZONTAL_VELOCITY = 5
PADDLE_INITIAL_X_POSITION = WIDTH / 2
PADDLE_INITIAL_Y_POSITION = HEIGHT - 100
PADDLE_BOUNCE_X_FACTOR = 3

# brick
BRICKS_AMOUNT_PER_LINE = 10
MAX_LINES_OF_BRICKS_AMOUNT = 10
BRICK_WIDTH = 75
BRICK_HEIGHT = 25

# ball
BALL_WIDTH = 20
BALL_HEIGHT = 20
BALL_ABSOLUTE_VERTICAL_VELOCITY = 6
BALL_INITIAL_X_POSITION = PADDLE_INITIAL_X_POSITION + PADDLE_WIDTH / 2 - BALL_WIDTH / 2
BALL_INITIAL_Y_POSITION = PADDLE_INITIAL_Y_POSITION - BALL_HEIGHT
BALL_ABSOLUTE_MAXIMUM_INITIAL_HORIZONTAL_VELOCITY = 6

# game controller
LIVES_LABEL = "Lives: "
POINTS_LABEL = "Points: "
LEVEL_LABEL = "Level: "
GAME_LABELS_MARGIN = 10
GAME_LABELS_COLOR = (255, 255, 255)

# pause controller
PAUSE_TITLE = "PAUSE"
PAUSE_TITLE_COLOR = (255, 255, 255)
PAUSE_TITLE_Y_POSITION = 100
PAUSE_MENU_RESUME_ITEM_TEXT = "RESUME"
PAUSE_MENU_EXIT_ITEM_TEXT = "EXIT"
PAUSE_LABELS_COLOR = (255, 255, 255)
PAUSE_MENU_ITEM_TOP_MARGIN = 20

# win controller
WIN_TITLE = "YOU WON!"
WIN_TITLE_COLOR = (255, 255, 255)
WIN_TITLE_Y_POSITION = 100
WIN_SCORE_TEXT = "Points scored: "
WIN_CONTINUE_TEXT = "Press RETURN to continue"
WIN_LABELS_COLOR = (255, 255, 255)
WIN_LABELS_TOP_MARGIN = 20

# lose controller
LOSE_TITLE = "YOU LOST!"
LOSE_TITLE_COLOR = (255, 255, 255)
LOSE_TITLE_Y_POSITION = 100
LOSE_SCORE_TEXT = "Points scored: "
LOSE_CONTINUE_TEXT = "Press RETURN to continue"
LOSE_LABELS_COLOR = (255, 255, 255)
LOSE_LABELS_TOP_MARGIN = 20
